# Should match the version used in production
FROM nginx:1.29@sha256:1881968aff6f7cdcc4b888c00a11f4ce241ad7ec957e0cb4a9e19e93a3ff87ea

RUN apt-get -q update \
    && apt-get -q --yes install ncat \
    && apt-get clean
