# Should match the version used in production
FROM nginx:1.31@sha256:f9ea18bfa4fad859e1ed38259d711da7ccad2c3516e875cec3351a57c859f571

RUN apt-get -q update \
    && apt-get -q --yes install ncat \
    && apt-get clean
