# Should match the version used in production
FROM nginx:1.31@sha256:05b8cb60c354a44ab824ea6e7dc69b46d50762cdbe728a347a5b656e6fb3d7c4

RUN apt-get -q update \
    && apt-get -q --yes install ncat \
    && apt-get clean
